package io.github.chris2011.netbeans.plugins.consolebeans;

import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
//@ConvertAsProperties(dtd = "-//org.stagezero.jconsole//JConsole//EN", autostore = false)
@TopComponent.Description(preferredID = "ConsoleTopComponent", persistenceType = TopComponent.PERSISTENCE_NEVER/*, iconBase="SET/PATH/TO/ICON/HERE",*/)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "org.stagezero.jconsole.JConsoleTopComponent")
@ActionReference(path = "Menu/Window/IDE Tools"/*, position = 333*/)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ConsoleAction", preferredID = "ConsoleTopComponent")
@Messages({
    "CTL_ConsoleAction=Console",
    "CTL_ConsoleTopComponent=Console",
    "HINT_ConsoleTopComponent=This is a Console window"
})
public final class ConsoleTopComponent extends TopComponent {

    public ConsoleTopComponent() {
        initComponents();
        setName(Bundle.CTL_ConsoleTopComponent());
        setToolTipText(Bundle.HINT_ConsoleTopComponent());

        initialSplitPane.setResizeWeight(0.5);
        initialSplitPane.setOneTouchExpandable(true);
        initialSplitPane.setContinuousLayout(true);
        initialSplitPane.setDividerSize(0);
        initialSplitPane.setRightComponent(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutPanel = new javax.swing.JPanel();
        toolbarPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        consolePanel = new javax.swing.JPanel();
        initialSplitPane = new javax.swing.JSplitPane();
        initialScrollPane = new javax.swing.JScrollPane();
        jconsoleDisplay = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(1, 0));

        layoutPanel.setPreferredSize(new java.awt.Dimension(0, 30));

        toolbarPanel.setPreferredSize(new java.awt.Dimension(0, 25));

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(ConsoleTopComponent.class, "ConsoleTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(ConsoleTopComponent.class, "ConsoleTopComponent.jButton2.text")); // NOI18N

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        jconsoleDisplay.setColumns(20);
        jconsoleDisplay.setRows(5);
        jconsoleDisplay.setMargin(new java.awt.Insets(0, 6, 2, 6));
        initialScrollPane.setViewportView(jconsoleDisplay);

        initialSplitPane.setLeftComponent(initialScrollPane);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initialSplitPane)
                .addContainerGap())
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(initialSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layoutPanelLayout = new javax.swing.GroupLayout(layoutPanel);
        layoutPanel.setLayout(layoutPanelLayout);
        layoutPanelLayout.setHorizontalGroup(
            layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
            .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layoutPanelLayout.setVerticalGroup(
            layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutPanelLayout.createSequentialGroup()
                .addComponent(toolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(layoutPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextArea consoleDisplay = new JTextArea();

        consoleDisplay.setColumns(20);
        consoleDisplay.setRows(5);
        consoleDisplay.setMargin(new java.awt.Insets(5, 6, 2, 6));

        try {
            Console newConsole = new Console(consoleDisplay);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
            JOptionPane.showMessageDialog(null, ex);
        }

        JScrollPane newRightScrollPane = new JScrollPane();
        newRightScrollPane.setViewportView(consoleDisplay);
        
        JSplitPane newSplitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, initialSplitPane, newRightScrollPane);

        newSplitPane.setResizeWeight(0.5);
        newSplitPane.setOneTouchExpandable(true);
        newSplitPane.setContinuousLayout(true);
        newSplitPane.setDividerSize(0);

        initialSplitPane.setDividerSize(5);
//        initialSplitPane = newSplitPane;
//        initialSplitPane.removeAll();
        initialSplitPane.add(newSplitPane);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel consolePanel;
    private javax.swing.JScrollPane initialScrollPane;
    private javax.swing.JSplitPane initialSplitPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextArea jconsoleDisplay;
    private javax.swing.JPanel layoutPanel;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables
    private Console console;

    @Override
    public void componentOpened() {
        try {
//            // TODO add custom code on component opening
//            if (console == null) {
            console = new Console(jconsoleDisplay);
//            }
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        if (console != null) {
            console.close();
            console = null;
        }
    }

//    void writeProperties(java.util.Properties p) {
//        // better to version settings since initial version as advocated at
//        // http://wiki.apidesign.org/wiki/PropertyFiles
//        p.setProperty("version", "1.0");
//        // TODO store your settings
//    }
//
//    void readProperties(java.util.Properties p) {
//        String version = p.getProperty("version");
//        // TODO read your settings according to their version
//    }
}
